# Docker Compose configuration for Windows
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.windows
    ports:
      - "8000:8000"
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      - ./app:/app
    networks:
      - qtai-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.windows
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - qtai-network

networks:
  qtai-network:
    driver: bridge
